---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - mqttclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - mqttclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - orca.paermini.com
  resources:
  - opcuaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - opcuaservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - orca.paermini.com
  resources:
  - scenarios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - scenarios/finalizers
  verbs:
  - update
- apiGroups:
  - orca.paermini.com
  resources:
  - scenarios/status
  verbs:
  - get
  - patch
  - update
