# permissions for end users to edit scenarios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scenario-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orca-scenario
    app.kubernetes.io/part-of: orca-scenario
    app.kubernetes.io/managed-by: kustomize
  name: scenario-editor-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - scenarios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - scenarios/status
  verbs:
  - get
